language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
script:
    nohup npm run start &
    sleep 10